# Generated by Django 3.2.7 on 2021-12-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbienvenida', '0002_auto_20211201_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Correo',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_Usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
