# Generated by Django 3.2.7 on 2021-12-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbienvenida', '0004_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
