# Generated by Django 3.2.7 on 2021-12-10 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbienvenida', '0005_delete_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_Archivo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(default='', max_length=45)),
                ('media', models.FileField(blank=True, null=True, upload_to='myfolder/')),
                ('usuario_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
