# Generated by Django 3.2.7 on 2021-12-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Ap_paterno', models.CharField(max_length=45)),
                ('Ap_materno', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=50)),
            ],
        ),
    ]
